/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './pages/_auth/forgot-password'
import { Route as AppDashboardRouteImport } from './pages/_app/dashboard'
import { Route as AppOrganizationSlugRouteImport } from './pages/_app/$organizationSlug'
import { Route as WebhookOauthCallbackRouteImport } from './pages/webhook/oauth/callback'
import { Route as AuthResetPasswordTokenRouteImport } from './pages/_auth/reset-password.$token'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './pages/_auth/accept-invitation.$invitationId'
import { Route as AppOrganizationSlugSettingsRouteImport } from './pages/_app/$organizationSlug/settings'
import { Route as AppOrganizationSlugOrganizationRouteImport } from './pages/_app/$organizationSlug/organization'
import { Route as AppOrganizationSlugDashboardRouteImport } from './pages/_app/$organizationSlug/dashboard'
import { Route as AppOrganizationSlugWebhooksIndexRouteImport } from './pages/_app/$organizationSlug/webhooks/index'
import { Route as AppOrganizationSlugApiKeysIndexRouteImport } from './pages/_app/$organizationSlug/api-keys/index'
import { Route as AppOrganizationSlugWhatsappConnectRouteImport } from './pages/_app/$organizationSlug/whatsapp/connect'
import { Route as AppOrganizationSlugWhatsappTemplatesIndexRouteImport } from './pages/_app/$organizationSlug/whatsapp/templates/index'
import { Route as AppOrganizationSlugWhatsappChatIndexRouteImport } from './pages/_app/$organizationSlug/whatsapp/chat/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrganizationSlugRoute = AppOrganizationSlugRouteImport.update({
  id: '/$organizationSlug',
  path: '/$organizationSlug',
  getParentRoute: () => AppLayoutRoute,
} as any)
const WebhookOauthCallbackRoute = WebhookOauthCallbackRouteImport.update({
  id: '/webhook/oauth/callback',
  path: '/webhook/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AppOrganizationSlugSettingsRoute =
  AppOrganizationSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppOrganizationSlugRoute,
  } as any)
const AppOrganizationSlugOrganizationRoute =
  AppOrganizationSlugOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AppOrganizationSlugRoute,
  } as any)
const AppOrganizationSlugDashboardRoute =
  AppOrganizationSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppOrganizationSlugRoute,
  } as any)
const AppOrganizationSlugWebhooksIndexRoute =
  AppOrganizationSlugWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AppOrganizationSlugRoute,
  } as any)
const AppOrganizationSlugApiKeysIndexRoute =
  AppOrganizationSlugApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AppOrganizationSlugRoute,
  } as any)
const AppOrganizationSlugWhatsappConnectRoute =
  AppOrganizationSlugWhatsappConnectRouteImport.update({
    id: '/whatsapp/connect',
    path: '/whatsapp/connect',
    getParentRoute: () => AppOrganizationSlugRoute,
  } as any)
const AppOrganizationSlugWhatsappTemplatesIndexRoute =
  AppOrganizationSlugWhatsappTemplatesIndexRouteImport.update({
    id: '/whatsapp/templates/',
    path: '/whatsapp/templates/',
    getParentRoute: () => AppOrganizationSlugRoute,
  } as any)
const AppOrganizationSlugWhatsappChatIndexRoute =
  AppOrganizationSlugWhatsappChatIndexRouteImport.update({
    id: '/whatsapp/chat/',
    path: '/whatsapp/chat/',
    getParentRoute: () => AppOrganizationSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$organizationSlug': typeof AppOrganizationSlugRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$organizationSlug/dashboard': typeof AppOrganizationSlugDashboardRoute
  '/$organizationSlug/organization': typeof AppOrganizationSlugOrganizationRoute
  '/$organizationSlug/settings': typeof AppOrganizationSlugSettingsRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/webhook/oauth/callback': typeof WebhookOauthCallbackRoute
  '/$organizationSlug/whatsapp/connect': typeof AppOrganizationSlugWhatsappConnectRoute
  '/$organizationSlug/api-keys': typeof AppOrganizationSlugApiKeysIndexRoute
  '/$organizationSlug/webhooks': typeof AppOrganizationSlugWebhooksIndexRoute
  '/$organizationSlug/whatsapp/chat': typeof AppOrganizationSlugWhatsappChatIndexRoute
  '/$organizationSlug/whatsapp/templates': typeof AppOrganizationSlugWhatsappTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$organizationSlug': typeof AppOrganizationSlugRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$organizationSlug/dashboard': typeof AppOrganizationSlugDashboardRoute
  '/$organizationSlug/organization': typeof AppOrganizationSlugOrganizationRoute
  '/$organizationSlug/settings': typeof AppOrganizationSlugSettingsRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/webhook/oauth/callback': typeof WebhookOauthCallbackRoute
  '/$organizationSlug/whatsapp/connect': typeof AppOrganizationSlugWhatsappConnectRoute
  '/$organizationSlug/api-keys': typeof AppOrganizationSlugApiKeysIndexRoute
  '/$organizationSlug/webhooks': typeof AppOrganizationSlugWebhooksIndexRoute
  '/$organizationSlug/whatsapp/chat': typeof AppOrganizationSlugWhatsappChatIndexRoute
  '/$organizationSlug/whatsapp/templates': typeof AppOrganizationSlugWhatsappTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/$organizationSlug': typeof AppOrganizationSlugRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/$organizationSlug/dashboard': typeof AppOrganizationSlugDashboardRoute
  '/_app/$organizationSlug/organization': typeof AppOrganizationSlugOrganizationRoute
  '/_app/$organizationSlug/settings': typeof AppOrganizationSlugSettingsRoute
  '/_auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/webhook/oauth/callback': typeof WebhookOauthCallbackRoute
  '/_app/$organizationSlug/whatsapp/connect': typeof AppOrganizationSlugWhatsappConnectRoute
  '/_app/$organizationSlug/api-keys/': typeof AppOrganizationSlugApiKeysIndexRoute
  '/_app/$organizationSlug/webhooks/': typeof AppOrganizationSlugWebhooksIndexRoute
  '/_app/$organizationSlug/whatsapp/chat/': typeof AppOrganizationSlugWhatsappChatIndexRoute
  '/_app/$organizationSlug/whatsapp/templates/': typeof AppOrganizationSlugWhatsappTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizationSlug'
    | '/dashboard'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/$organizationSlug/dashboard'
    | '/$organizationSlug/organization'
    | '/$organizationSlug/settings'
    | '/accept-invitation/$invitationId'
    | '/reset-password/$token'
    | '/webhook/oauth/callback'
    | '/$organizationSlug/whatsapp/connect'
    | '/$organizationSlug/api-keys'
    | '/$organizationSlug/webhooks'
    | '/$organizationSlug/whatsapp/chat'
    | '/$organizationSlug/whatsapp/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$organizationSlug'
    | '/dashboard'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/$organizationSlug/dashboard'
    | '/$organizationSlug/organization'
    | '/$organizationSlug/settings'
    | '/accept-invitation/$invitationId'
    | '/reset-password/$token'
    | '/webhook/oauth/callback'
    | '/$organizationSlug/whatsapp/connect'
    | '/$organizationSlug/api-keys'
    | '/$organizationSlug/webhooks'
    | '/$organizationSlug/whatsapp/chat'
    | '/$organizationSlug/whatsapp/templates'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/$organizationSlug'
    | '/_app/dashboard'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/$organizationSlug/dashboard'
    | '/_app/$organizationSlug/organization'
    | '/_app/$organizationSlug/settings'
    | '/_auth/accept-invitation/$invitationId'
    | '/_auth/reset-password/$token'
    | '/webhook/oauth/callback'
    | '/_app/$organizationSlug/whatsapp/connect'
    | '/_app/$organizationSlug/api-keys/'
    | '/_app/$organizationSlug/webhooks/'
    | '/_app/$organizationSlug/whatsapp/chat/'
    | '/_app/$organizationSlug/whatsapp/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  WebhookOauthCallbackRoute: typeof WebhookOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/$organizationSlug': {
      id: '/_app/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof AppOrganizationSlugRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/webhook/oauth/callback': {
      id: '/webhook/oauth/callback'
      path: '/webhook/oauth/callback'
      fullPath: '/webhook/oauth/callback'
      preLoaderRoute: typeof WebhookOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password/$token': {
      id: '/_auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/accept-invitation/$invitationId': {
      id: '/_auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/$organizationSlug/settings': {
      id: '/_app/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/$organizationSlug/settings'
      preLoaderRoute: typeof AppOrganizationSlugSettingsRouteImport
      parentRoute: typeof AppOrganizationSlugRoute
    }
    '/_app/$organizationSlug/organization': {
      id: '/_app/$organizationSlug/organization'
      path: '/organization'
      fullPath: '/$organizationSlug/organization'
      preLoaderRoute: typeof AppOrganizationSlugOrganizationRouteImport
      parentRoute: typeof AppOrganizationSlugRoute
    }
    '/_app/$organizationSlug/dashboard': {
      id: '/_app/$organizationSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$organizationSlug/dashboard'
      preLoaderRoute: typeof AppOrganizationSlugDashboardRouteImport
      parentRoute: typeof AppOrganizationSlugRoute
    }
    '/_app/$organizationSlug/webhooks/': {
      id: '/_app/$organizationSlug/webhooks/'
      path: '/webhooks'
      fullPath: '/$organizationSlug/webhooks'
      preLoaderRoute: typeof AppOrganizationSlugWebhooksIndexRouteImport
      parentRoute: typeof AppOrganizationSlugRoute
    }
    '/_app/$organizationSlug/api-keys/': {
      id: '/_app/$organizationSlug/api-keys/'
      path: '/api-keys'
      fullPath: '/$organizationSlug/api-keys'
      preLoaderRoute: typeof AppOrganizationSlugApiKeysIndexRouteImport
      parentRoute: typeof AppOrganizationSlugRoute
    }
    '/_app/$organizationSlug/whatsapp/connect': {
      id: '/_app/$organizationSlug/whatsapp/connect'
      path: '/whatsapp/connect'
      fullPath: '/$organizationSlug/whatsapp/connect'
      preLoaderRoute: typeof AppOrganizationSlugWhatsappConnectRouteImport
      parentRoute: typeof AppOrganizationSlugRoute
    }
    '/_app/$organizationSlug/whatsapp/templates/': {
      id: '/_app/$organizationSlug/whatsapp/templates/'
      path: '/whatsapp/templates'
      fullPath: '/$organizationSlug/whatsapp/templates'
      preLoaderRoute: typeof AppOrganizationSlugWhatsappTemplatesIndexRouteImport
      parentRoute: typeof AppOrganizationSlugRoute
    }
    '/_app/$organizationSlug/whatsapp/chat/': {
      id: '/_app/$organizationSlug/whatsapp/chat/'
      path: '/whatsapp/chat'
      fullPath: '/$organizationSlug/whatsapp/chat'
      preLoaderRoute: typeof AppOrganizationSlugWhatsappChatIndexRouteImport
      parentRoute: typeof AppOrganizationSlugRoute
    }
  }
}

interface AppOrganizationSlugRouteChildren {
  AppOrganizationSlugDashboardRoute: typeof AppOrganizationSlugDashboardRoute
  AppOrganizationSlugOrganizationRoute: typeof AppOrganizationSlugOrganizationRoute
  AppOrganizationSlugSettingsRoute: typeof AppOrganizationSlugSettingsRoute
  AppOrganizationSlugWhatsappConnectRoute: typeof AppOrganizationSlugWhatsappConnectRoute
  AppOrganizationSlugApiKeysIndexRoute: typeof AppOrganizationSlugApiKeysIndexRoute
  AppOrganizationSlugWebhooksIndexRoute: typeof AppOrganizationSlugWebhooksIndexRoute
  AppOrganizationSlugWhatsappChatIndexRoute: typeof AppOrganizationSlugWhatsappChatIndexRoute
  AppOrganizationSlugWhatsappTemplatesIndexRoute: typeof AppOrganizationSlugWhatsappTemplatesIndexRoute
}

const AppOrganizationSlugRouteChildren: AppOrganizationSlugRouteChildren = {
  AppOrganizationSlugDashboardRoute: AppOrganizationSlugDashboardRoute,
  AppOrganizationSlugOrganizationRoute: AppOrganizationSlugOrganizationRoute,
  AppOrganizationSlugSettingsRoute: AppOrganizationSlugSettingsRoute,
  AppOrganizationSlugWhatsappConnectRoute:
    AppOrganizationSlugWhatsappConnectRoute,
  AppOrganizationSlugApiKeysIndexRoute: AppOrganizationSlugApiKeysIndexRoute,
  AppOrganizationSlugWebhooksIndexRoute: AppOrganizationSlugWebhooksIndexRoute,
  AppOrganizationSlugWhatsappChatIndexRoute:
    AppOrganizationSlugWhatsappChatIndexRoute,
  AppOrganizationSlugWhatsappTemplatesIndexRoute:
    AppOrganizationSlugWhatsappTemplatesIndexRoute,
}

const AppOrganizationSlugRouteWithChildren =
  AppOrganizationSlugRoute._addFileChildren(AppOrganizationSlugRouteChildren)

interface AppLayoutRouteChildren {
  AppOrganizationSlugRoute: typeof AppOrganizationSlugRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppOrganizationSlugRoute: AppOrganizationSlugRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  WebhookOauthCallbackRoute: WebhookOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
