/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './pages/_auth/forgot-password'
import { Route as AppSettingsRouteImport } from './pages/_app/settings'
import { Route as AppDashboardRouteImport } from './pages/_app/dashboard'
import { Route as AuthResetPasswordTokenRouteImport } from './pages/_auth/reset-password.$token'
import { Route as AppRentalEquipmentIndexRouteImport } from './pages/_app/rental/equipment/index'
import { Route as AppRentalCategoriesIndexRouteImport } from './pages/_app/rental/categories/index'
import { Route as AppRentalBudgetsIndexRouteImport } from './pages/_app/rental/budgets/index'
import { Route as AppRentalBudgetsBudgetIdIndexRouteImport } from './pages/_app/rental/budgets/$budgetId/index'
import { Route as WRentalBudgetsBudgetIdPrintRouteImport } from './pages/w/rental/budgets/$budgetId/print'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppRentalEquipmentIndexRoute = AppRentalEquipmentIndexRouteImport.update({
  id: '/rental/equipment/',
  path: '/rental/equipment/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRentalCategoriesIndexRoute =
  AppRentalCategoriesIndexRouteImport.update({
    id: '/rental/categories/',
    path: '/rental/categories/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRentalBudgetsIndexRoute = AppRentalBudgetsIndexRouteImport.update({
  id: '/rental/budgets/',
  path: '/rental/budgets/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRentalBudgetsBudgetIdIndexRoute =
  AppRentalBudgetsBudgetIdIndexRouteImport.update({
    id: '/rental/budgets/$budgetId/',
    path: '/rental/budgets/$budgetId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const WRentalBudgetsBudgetIdPrintRoute =
  WRentalBudgetsBudgetIdPrintRouteImport.update({
    id: '/w/rental/budgets/$budgetId/print',
    path: '/w/rental/budgets/$budgetId/print',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/rental/budgets': typeof AppRentalBudgetsIndexRoute
  '/rental/categories': typeof AppRentalCategoriesIndexRoute
  '/rental/equipment': typeof AppRentalEquipmentIndexRoute
  '/w/rental/budgets/$budgetId/print': typeof WRentalBudgetsBudgetIdPrintRoute
  '/rental/budgets/$budgetId': typeof AppRentalBudgetsBudgetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/rental/budgets': typeof AppRentalBudgetsIndexRoute
  '/rental/categories': typeof AppRentalCategoriesIndexRoute
  '/rental/equipment': typeof AppRentalEquipmentIndexRoute
  '/w/rental/budgets/$budgetId/print': typeof WRentalBudgetsBudgetIdPrintRoute
  '/rental/budgets/$budgetId': typeof AppRentalBudgetsBudgetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/_app/rental/budgets/': typeof AppRentalBudgetsIndexRoute
  '/_app/rental/categories/': typeof AppRentalCategoriesIndexRoute
  '/_app/rental/equipment/': typeof AppRentalEquipmentIndexRoute
  '/w/rental/budgets/$budgetId/print': typeof WRentalBudgetsBudgetIdPrintRoute
  '/_app/rental/budgets/$budgetId/': typeof AppRentalBudgetsBudgetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/reset-password/$token'
    | '/rental/budgets'
    | '/rental/categories'
    | '/rental/equipment'
    | '/w/rental/budgets/$budgetId/print'
    | '/rental/budgets/$budgetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/reset-password/$token'
    | '/rental/budgets'
    | '/rental/categories'
    | '/rental/equipment'
    | '/w/rental/budgets/$budgetId/print'
    | '/rental/budgets/$budgetId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/reset-password/$token'
    | '/_app/rental/budgets/'
    | '/_app/rental/categories/'
    | '/_app/rental/equipment/'
    | '/w/rental/budgets/$budgetId/print'
    | '/_app/rental/budgets/$budgetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  WRentalBudgetsBudgetIdPrintRoute: typeof WRentalBudgetsBudgetIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/reset-password/$token': {
      id: '/_auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/rental/equipment/': {
      id: '/_app/rental/equipment/'
      path: '/rental/equipment'
      fullPath: '/rental/equipment'
      preLoaderRoute: typeof AppRentalEquipmentIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/rental/categories/': {
      id: '/_app/rental/categories/'
      path: '/rental/categories'
      fullPath: '/rental/categories'
      preLoaderRoute: typeof AppRentalCategoriesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/rental/budgets/': {
      id: '/_app/rental/budgets/'
      path: '/rental/budgets'
      fullPath: '/rental/budgets'
      preLoaderRoute: typeof AppRentalBudgetsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/rental/budgets/$budgetId/': {
      id: '/_app/rental/budgets/$budgetId/'
      path: '/rental/budgets/$budgetId'
      fullPath: '/rental/budgets/$budgetId'
      preLoaderRoute: typeof AppRentalBudgetsBudgetIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/w/rental/budgets/$budgetId/print': {
      id: '/w/rental/budgets/$budgetId/print'
      path: '/w/rental/budgets/$budgetId/print'
      fullPath: '/w/rental/budgets/$budgetId/print'
      preLoaderRoute: typeof WRentalBudgetsBudgetIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppLayoutRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppRentalBudgetsIndexRoute: typeof AppRentalBudgetsIndexRoute
  AppRentalCategoriesIndexRoute: typeof AppRentalCategoriesIndexRoute
  AppRentalEquipmentIndexRoute: typeof AppRentalEquipmentIndexRoute
  AppRentalBudgetsBudgetIdIndexRoute: typeof AppRentalBudgetsBudgetIdIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppRentalBudgetsIndexRoute: AppRentalBudgetsIndexRoute,
  AppRentalCategoriesIndexRoute: AppRentalCategoriesIndexRoute,
  AppRentalEquipmentIndexRoute: AppRentalEquipmentIndexRoute,
  AppRentalBudgetsBudgetIdIndexRoute: AppRentalBudgetsBudgetIdIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  WRentalBudgetsBudgetIdPrintRoute: WRentalBudgetsBudgetIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
