/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AuthSignUpRouteImport } from './pages/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './pages/_auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './pages/_auth/forgot-password'
import { Route as AppSettingsRouteImport } from './pages/_app/settings'
import { Route as AppOrganizationRouteImport } from './pages/_app/organization'
import { Route as AppDashboardRouteImport } from './pages/_app/dashboard'
import { Route as WebhookOauthCallbackRouteImport } from './pages/webhook/oauth/callback'
import { Route as AuthResetPasswordTokenRouteImport } from './pages/_auth/reset-password.$token'
import { Route as AuthAcceptInvitationInvitationIdRouteImport } from './pages/_auth/accept-invitation.$invitationId'
import { Route as AppWhatsappConnectRouteImport } from './pages/_app/whatsapp/connect'
import { Route as AppWhatsappTemplatesIndexRouteImport } from './pages/_app/whatsapp/templates/index'
import { Route as AppWhatsappChatIndexRouteImport } from './pages/_app/whatsapp/chat/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppLayoutRoute,
} as any)
const WebhookOauthCallbackRoute = WebhookOauthCallbackRouteImport.update({
  id: '/webhook/oauth/callback',
  path: '/webhook/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AppWhatsappConnectRoute = AppWhatsappConnectRouteImport.update({
  id: '/whatsapp/connect',
  path: '/whatsapp/connect',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppWhatsappTemplatesIndexRoute =
  AppWhatsappTemplatesIndexRouteImport.update({
    id: '/whatsapp/templates/',
    path: '/whatsapp/templates/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppWhatsappChatIndexRoute = AppWhatsappChatIndexRouteImport.update({
  id: '/whatsapp/chat/',
  path: '/whatsapp/chat/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/whatsapp/connect': typeof AppWhatsappConnectRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/webhook/oauth/callback': typeof WebhookOauthCallbackRoute
  '/whatsapp/chat': typeof AppWhatsappChatIndexRoute
  '/whatsapp/templates': typeof AppWhatsappTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/organization': typeof AppOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/whatsapp/connect': typeof AppWhatsappConnectRoute
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/webhook/oauth/callback': typeof WebhookOauthCallbackRoute
  '/whatsapp/chat': typeof AppWhatsappChatIndexRoute
  '/whatsapp/templates': typeof AppWhatsappTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/organization': typeof AppOrganizationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/whatsapp/connect': typeof AppWhatsappConnectRoute
  '/_auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/webhook/oauth/callback': typeof WebhookOauthCallbackRoute
  '/_app/whatsapp/chat/': typeof AppWhatsappChatIndexRoute
  '/_app/whatsapp/templates/': typeof AppWhatsappTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/whatsapp/connect'
    | '/accept-invitation/$invitationId'
    | '/reset-password/$token'
    | '/webhook/oauth/callback'
    | '/whatsapp/chat'
    | '/whatsapp/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/whatsapp/connect'
    | '/accept-invitation/$invitationId'
    | '/reset-password/$token'
    | '/webhook/oauth/callback'
    | '/whatsapp/chat'
    | '/whatsapp/templates'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/organization'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/whatsapp/connect'
    | '/_auth/accept-invitation/$invitationId'
    | '/_auth/reset-password/$token'
    | '/webhook/oauth/callback'
    | '/_app/whatsapp/chat/'
    | '/_app/whatsapp/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  WebhookOauthCallbackRoute: typeof WebhookOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/organization': {
      id: '/_app/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/webhook/oauth/callback': {
      id: '/webhook/oauth/callback'
      path: '/webhook/oauth/callback'
      fullPath: '/webhook/oauth/callback'
      preLoaderRoute: typeof WebhookOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password/$token': {
      id: '/_auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/accept-invitation/$invitationId': {
      id: '/_auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/whatsapp/connect': {
      id: '/_app/whatsapp/connect'
      path: '/whatsapp/connect'
      fullPath: '/whatsapp/connect'
      preLoaderRoute: typeof AppWhatsappConnectRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/whatsapp/templates/': {
      id: '/_app/whatsapp/templates/'
      path: '/whatsapp/templates'
      fullPath: '/whatsapp/templates'
      preLoaderRoute: typeof AppWhatsappTemplatesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/whatsapp/chat/': {
      id: '/_app/whatsapp/chat/'
      path: '/whatsapp/chat'
      fullPath: '/whatsapp/chat'
      preLoaderRoute: typeof AppWhatsappChatIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWhatsappConnectRoute: typeof AppWhatsappConnectRoute
  AppWhatsappChatIndexRoute: typeof AppWhatsappChatIndexRoute
  AppWhatsappTemplatesIndexRoute: typeof AppWhatsappTemplatesIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWhatsappConnectRoute: AppWhatsappConnectRoute,
  AppWhatsappChatIndexRoute: AppWhatsappChatIndexRoute,
  AppWhatsappTemplatesIndexRoute: AppWhatsappTemplatesIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  WebhookOauthCallbackRoute: WebhookOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
